# name of your application
APPLICATION = octa-stm-example
APPLICATION_VERSION = 0.2.0

# platform for which the application will be built
PLATFORM ?= octa_stm

DEBUG = 1

# Set PRINT_FLOATS to 1 to enable linker flags enabling float printf & sprintf
PRINT_FLOATS = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core