# name of your application
APPLICATION = gps-firefly-example

# platform for which the application will be built
PLATFORM ?= octa

# Set PRINT_FLOATS to 1 to enable linker flags enabling float printf & sprintf
PRINT_FLOATS = 1

# Add shields used in application
# GPS-Firefly
SHIELDS += gps-firefly
FIREFLY_CONNECTOR = 3

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core