# name of your application
APPLICATION = no-scheduler-example
APPLICATION_VERSION = 0.2.0

# don't use RTOS scheduler for this example
USE_RTOS_SCHEDULER = 0

# platform for which the application will be built
PLATFORM ?= octa

# use the SBSFU bootloader
BOOTLOADER ?= 0

LOW_POWER = 0

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core