# name of your application
APPLICATION = no-scheduler-example

# platform for which the application will be built
PLATFORM ?= octa

# use the SBSFU bootloader
BOOTLOADER ?= 0

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core