# name of your application
APPLICATION = lorawan-example

# platform for which the application will be built
PLATFORM ?= octa

# Add shields used in application
# Murata
SHIELDS += Murata
MURATA_CONNECTOR = 3
LORAWAN_APPLICATION = iowttn

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core