NOVA_PM_VERSION = 0.1.0

# Nova PM sensor sources
C_SOURCES += $(wildcard $(SHIELDS_DIR)/nova_PM_sensor/src/*.c)

# Nova PM sensor includes
C_INCLUDES += -I$(SHIELDS_DIR)/nova_PM_sensor/inc

ifeq ($(origin NOVA_PM_CONNECTOR), undefined)
$(error NOVA_PM_CONNECTOR undefined in makefile, please specify a connector in the application makefile)
endif

SHIELD_DEFINES += -DNOVA_PM_CONNECTOR=$(NOVA_PM_CONNECTOR)
SHIELD_DEFINES += -DNOVA_PM_VERSION="$(NOVA_PM_VERSION)"