/* MESSAGE TYPES */
#define TYPE_MESSAGE_COUNTER                        0
#define TYPE_TIMESTAMP                              1
#define TYPE_GPS_SHORT                              2
#define TYPE_GPS_LONG                               3
#define TYPE_TEMP                                   4
#define TYPE_RELATIVE_HUMIDITY                      5
#define TYPE_NO2                                    6
#define TYPE_CO2                                    7
#define TYPE_VOC_TOTAL                              8
#define TYPE_VOC_PREDICTION                         9
#define TYPE_VOC_RESISTANCE                         10
#define TYPE_PM1                                    11
#define TYPE_PM2_5                                  12
#define TYPE_PM10                                   13
#define TYPE_LIGHT                                  14
#define TYPE_O3                                     15
#define TYPE_NB_IOT_IMEI                            16
#define TYPE_EXPOSURE                               17
#define TYPE_COLOUR                                 18
#define TYPE_NB_IOT_SIGNAL_POWER                    19
#define TYPE_MESSAGE_COUNTER_LARGE                  20
#define TYPE_NB_IOT_IMSI                            21
#define TYPE_NB_IOT_CELLID                          22
#define TYPE_NB_IOT_TXPOWER                         23
#define TYPE_BATTERY_VOLTAGE                        24
#define TYPE_OCTA_STATUS                            25
#define TYPE_ROD_SENSORID                           26
#define TYPE_ROD_IMPEDANCE                          27
#define TYPE_ROD_IMPEDANCE_PHASE                    28
#define TYPE_ROD_ERROR                              29
#define TYPE_ROD_VOLTAGEA                           30
#define TYPE_ROD_VOLTAGEB                           31
#define TYPE_ROD_VOLTAGEC                           32
#define TYPE_ROD_TEMPERATURE                        33
#define TYPE_MESSAGE_COUNTER_EXTRA_LARGE            34
#define TYPE_INTERVAL_UPDATE_CONFIRMATION           35
#define TYPE_OCTA_ID                                36
#define TYPE_DNS_UPDATE_CONFIRMATION                37
#define TYPE_CURRENT_FLASH_INDEX                    38
#define TYPE_APPLICATION_VERSION                    39
#define TYPE_STACK_VERSION                          40
#define TYPE_HEARTBEAT_INTERVAL                     41
#define TYPE_WELCOME_MESSAGE                        42
#define TYPE_DATA_TYPE_LIST                         43
#define TYPE_CONFIGURABLE_SETTINGS_LIST             44
#define TYPE_MIN_MAX_CUR_CONFIGURABLE_SETTING       45
#define TYPE_CUR_CONFIGURABLE_SETTING               46
#define TYPE_DEVICE_HEALTH_PARAM                    47
#define TYPE_HEARTBEAT_MESSAGE                      48


/* DOWNLINKS */
#define TYPE_DOWNLINK_DNS_UPDATE                    245
#define TYPE_DOWNLINK_INTERVAL_MULTIPLIER_UPDATE    246
#define TYPE_DOWNLINK_ACK                           247