# name of your application
APPLICATION = acc-mag-sensor
APPLICATION_VERSION = 0.1.0

# platform for which the application will be built
PLATFORM ?= octa

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core