# name of your application
APPLICATION = dns-example
APPLICATION_VERSION = 0.2.0

# platform for which the application will be built
PLATFORM ?= octa

LOW_POWER ?= 1

DEBUG = 1

# NB-IoT
SHIELDS += NB-IoT
NB_IOT_CONNECTOR = 2
# Available providers: Orange, Proximus, Telenet
NB_IOT_PROVIDER = Orange
NB_IOT_SERVER = IDLAB_TESTING

# Set PRINT_FLOATS to 1 to enable linker flags enabling float printf & sprintf
PRINT_FLOATS = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core