# name of your application
APPLICATION = hello-world
APPLICATION_VERSION = 0.2.0

# platform for which the application will be built
PLATFORM ?= octa

# use the SBSFU bootloader
BOOTLOADER ?= 0

DEBUG = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core