# name of your application
APPLICATION = hello-world

# platform for which the application will be built
PLATFORM ?= octa

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core