# name of your application
APPLICATION = tickless-example
APPLICATION_VERSION = 0.4.0

# platform for which the application will be built
PLATFORM ?= octa

# Low power = 2 -> tickless mode
LOW_POWER = 2

USE_FTDI_LOGGING = 1

# DEBUG to enable more logging, disable for release
DEBUG = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core